### ISSUE TITLE
ZKNew fails to create a new note

### ISSUE THREAD

**Issue by megalithic** [megalithic/zk.nvim#1]
Presently `:ZkNew` fails to complete successfully due to the fact that `zk` needs to have its `cwd` set to a dir with an initialized notebook.

Possible solution is to allow a user to define minimal config to set the `zk_default_notebook_path` and all commands from that point forward would be run from that path as the `cwd`, using the `.zk` dir as a root marker.

See #2

**Comment by mickael-menu** [comment]
(Copying from https://github.com/mickael-menu/zk/discussions/11#discussioncomment-489636)

* `zk` works in any subdirectory of a notebook, `zk list` will display the paths relative to the working directory in this case.
    * However, sometimes it's useful to make sure the commands are ran from the root of the notebook, in case we use specific predefined paths (e.g. `-x log` to ignore the daily logs in the search).
    * I'm using [vim-rooter](https://github.com/airblade/vim-rooter) which conveniently moves the wd to the root of a file's Git repository if there's any. Since I also use Git in my notebook, that's enough. But maybe we could have something similar in `zk.nvim` to auto-cwd to the root of the current notebook.
* I think it makes sense to define a default notebook in `zk.nvim`'s config, to use with commands when not already in a notebook.
    * The cwd notebook should take precedence over the default one, otherwise this limits the plugin to a single notebook.
    * Would it help if `zk` returned a particular exit code meaning "not in a notebook"? This way you could first attempt the command in cwd, and fallback on the notebook in the config.

**Comment by megalithic** [comment]
Initial note creation (when in the correct / valid `cwd`) works; however, we don't have a way to `+autochdir` to that notebook's dir from some arbitrary starting `cwd`. 

Closing this issue to track #5.
