### ISSUE TITLE
Handle LSP things, similar to neuron's LS?

### ISSUE THREAD

**Issue by megalithic** [megalithic/zk.nvim#11]
https://github.com/aca/neuron-language-server

**Comment by mickael-menu** [comment]
That's a really interesting and promising approach! It could enable basic support for `zk` in any LSP-compatible editor. However, I wonder how well the Zettelkasten use cases match LSP which is made for programming languages. Do you have some idea @megalithic?

The repo you shared for neuron is small enough to be easily integrated with `zk`, for initial testing.

**Comment by mickael-menu** [comment]
The sourcegraph/go-lsp library used by the repo seems to be a bit obsolete, this one could be an alternative but still in early development: https://github.com/tliron/glsp

**Comment by mickael-menu** [comment]
@megalithic I've been experimenting a bit with this, and I'm confident this is the way forward for basic features: tags and links completion, following links, etc. `zk.nvim` can then be focused on more high-level features like showing backlinks.

I think I'll have something to show next week or the week after.

**Comment by megalithic** [comment]
Yes! That is fantastic and I agree

**Comment by mickael-menu** [comment]
Here's a teaser of tag completion ;) 

<img width="1058" alt="Screenshot 2021-03-28 at 20 25 28" src="https://user-images.githubusercontent.com/58686775/112763196-bfacb300-9003-11eb-99f2-92f93ae2ed4a.png">

We can also add some "documentation" next to the completion item, here I put the content of a random note. Neovim interprets the Markdown and formats it accordingly, so we will be able to have a nice preview of the notes when creating links 👍

**Comment by megalithic** [comment]
Perhaps we can nail down the actual features we want zk.nvim to have. I’ve sort of just been using zk.nvim to play around with creating my first nvim plugin in lua and to improve my own note taking system using zk at its core. With a zklsp potentially, it opens up an incredible suite of tools to fully manage and interact with your PKM all with in neovim.

**Comment by megalithic** [comment]
just cross-referencing to your open PR: https://github.com/mickael-menu/zk/pull/21

**Comment by mickael-menu** [comment]
Cross-referencing a dedicated issue tracking each LSP feature in `zk`: https://github.com/mickael-menu/zk/issues/22

**Comment by megalithic** [comment]
Closing this out and will continue to track in https://github.com/mickael-menu/zk
