### ISSUE TITLE
My configuration settings are being overridden by the default settings

### ISSUE THREAD

**Issue by nogweii** [megalithic/zk.nvim#26]
If I run `require('zk').setup({ fuzzy_finder = "telescope" })`, then print the contents of `zk_config`, I see "fzf" is set.

I believe it's because you got the order of the parameters backwards: https://github.com/megalithic/zk.nvim/blob/main/lua/zk/init.lua#L38 -- the implementation uses `vim.tbl_extend("force", ...)` which means the right-most values win, when it should be (in the current order) the other way around.

**Comment by nogweii** [comment]
Oh, this is fixed in #24 .

**Comment by mickael-menu** [comment]
I'm not sure @megalithic stills maintain `zk.nvim` but I'm going to merge the PR #24 as I have write access.
