### ISSUE TITLE
Creating wikilinks are broken

### ISSUE THREAD

**Issue by eric-hansen** [megalithic/zk.nvim#39]
If I try to create a note via code action it completely replaces the text with the link to the page (`[[yzcw]]` was originally `testing`) and the text isn't carried over to the page either.

If I use the default keymappings and hit enter over a word (highlighted or not), it gives the full path and is quoted, which then makes the LSP say it can't be found.

```markdown
This is a [[yzcw]] [['/home/ehansen/Projects/notebook/dvga.md'|for you]]

[['/home/ehansen/Projects/notebook/47id.md'|what]]
```

The cause for issue 2 above is here: https://github.com/megalithic/zk.nvim/blob/main/lua/zk/util.lua#L85  I'm really not sure why `shellescape` is being called on a filename.  But it would also fair better I think to be relative instead of absolute.

This is how I get it (I always call `nvim .`):

```lua
  local file = vim.fn['expand']('%:p')
  local relative_file = vim.fn['fnamemodify'](file, ':.:gs?//?/?')
```

It's not clean but it does the job and is moldable to this project.

**Comment by mickael-menu** [comment]
@eric-hansen This is supposed to be handled by the `zk` language server but I think `zk.nvim` is implementing this too and might be a bit outdated.

I personally don't use `zk.nvim` but I'm able to create a new note from the current selection with the vanilla LSP code actions. I'm using the following setup:

```
local lspconfig = require'lspconfig'
local configs = require'lspconfig/configs'

configs.zk = {
  default_config = {
    cmd = {'zk', 'lsp'};
    filetypes = {'markdown'};
    root_dir = lspconfig.util.root_pattern('.zk');
    settings = {};
  };
}

lspconfig.zk.setup({
  on_attach = function(client, bufnr)
    -- Key mappings
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local opts = { noremap=true, silent=true }

    -- Go to the linked note.
    buf_set_keymap("n", "<CR>", "<cmd>lua vim.lsp.buf.definition()<CR>", opts)
    -- Create a new note with the current selection.
    buf_set_keymap("v", "<CR>", ":'<,'>lua vim.lsp.buf.range_code_action()<CR>", opts)
  end
})
```
