### ISSUE TITLE
In-note linking to another note, or to a new note via FZF

### ISSUE THREAD

**Issue by megalithic** [megalithic/zk.nvim#6]
One major piece of functionality we'd like, is to be able to easily create a link from existing text in the current selection/buffer  to a new note with that selection text as a title, AND to be able to get an existing note/file and/or related note/file to the current one and link it in the current note..

Here's some examples of how to do it in straight up viml, using FZF and some other things:
https://github.com/joakin/.vim/blob/master/autoload/notes.vim

**Comment by mickael-menu** [comment]
Here are some parts that might be relevant from vim-zettel:

* [the \[\[ trigger](https://github.com/michal-h21/vim-zettel/blob/929d90eec62e6f693c2702d2b6f76a93f2f1689d/ftplugin/vimwiki/zettel.vim#L63)
* [the function doing the insertion after calling fzf](https://github.com/michal-h21/vim-zettel/blob/929d90eec62e6f693c2702d2b6f76a93f2f1689d/autoload/zettel/fzf.vim#L56-L73)

**Comment by megalithic** [comment]
More spots to look at for various linking techniques and things to do/handle linking: 

- https://www.reddit.com/r/Zettelkasten/comments/jmc3en/making_vimwiki_and_obsidian_attachments_play_well/

**Comment by mhanberg** [comment]
Honestly I think if this is implemented, I can start using zk on the daily.

**Comment by megalithic** [comment]
Yes! I'm actually working on this feature RIGHT NOW. i'm taking a couple days off tomorrow and friday and hoping to get through a few features to really get this plugin to a stable point of using on the daily (i use it daily as is, but there are several features that are missing that i want badly.. zk's new lsp features have bridged the major gap of what i was preparing to have to write).

**Comment by megalithic** [comment]
Initial implementation of this is complete: 
https://github.com/megalithic/zk.nvim#generate-a-new-note-and-inline-link

Further discussion on how to improve can be found here:
https://github.com/mickael-menu/zk/discussions/11#discussioncomment-601421
